import AppKit
import Foundation

/// 剪贴板敏感数据过滤与安全校验器
public struct ClipboardSecurityFilter {

    /// 自定义由 CalmBar 写入系统剪贴板时的标记类型，用于防止自身写回触发自循环
    public static let fromCalmBarType = NSPasteboard.PasteboardType("com.calmbar.fromCalmBar")

    /// 密码管理器与系统隐私相关的瞬态隐藏标记
    private static let sensitivePasteboardTypeNames: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.lastpass.LastPass",
        "de.keepassx.keepassxc",
        "com.bitwarden.desktop",
        "com.enpass.Enpass",
        "com.dashlane.DashlaneAgent",
        "com.nordpass.NordPass",
        "com.calmbar.fromCalmBar"
    ]

    /// 预设黑名单应用 Bundle ID（常见敏感工具）
    public static let defaultIgnoredAppBundles: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.macpack"
    ]

    /// 常见图片数据类型集合
    public static let imageTypes: Set<NSPasteboard.PasteboardType> = [
        .png,
        .tiff,
        NSPasteboard.PasteboardType("public.png"),
        NSPasteboard.PasteboardType("public.tiff"),
        NSPasteboard.PasteboardType("public.jpeg"),
        NSPasteboard.PasteboardType("public.heic"),
        NSPasteboard.PasteboardType("public.image"),
        NSPasteboard.PasteboardType("com.compuserve.gif"),
        NSPasteboard.PasteboardType("org.webmproject.webp"),
        NSPasteboard.PasteboardType("Apple PNG pasteboard type"),
        NSPasteboard.PasteboardType("Apple TIFF pasteboard type"),
        NSPasteboard.PasteboardType("NeXT TIFF v4.0 pasteboard type"),
        NSPasteboard.PasteboardType("com.apple.pict")
    ]

    /// 检查指定 NSPasteboardItem 是否应被忽略
    public static func shouldIgnore(
        item: NSPasteboardItem,
        sourceAppBundle: String? = nil,
        userIgnoredApps: [String] = [],
        filterSensitive: Bool = true
    ) -> Bool {
        let types = item.types

        // 1. 检查是否包含自身回写标记
        if types.contains(fromCalmBarType) {
            return true
        }

        // 2. 检查敏感类型
        if filterSensitive {
            let hasSensitiveType = types.contains { type in
                sensitivePasteboardTypeNames.contains(type.rawValue)
            }
            if hasSensitiveType {
                return true
            }
        }

        // 3. 检查来源应用是否在黑名单中
        if let bundle = sourceAppBundle {
            if defaultIgnoredAppBundles.contains(bundle) {
                return true
            }
            if userIgnoredApps.contains(bundle) {
                return true
            }
        }

        // 4. 检查是否有有效支持的数据类型 (图片 / 文本 / 文件)
        let hasImage = types.contains { imageTypes.contains($0) }
        let hasText = types.contains { $0 == .string || $0 == .rtf || $0 == .html || $0 == .color }
        let hasFile = types.contains { $0 == .fileURL }

        if !hasImage && !hasText && !hasFile {
            return true
        }

        // 5. 检查纯文本是否为空 (仅当不是图片和文件时才过滤空文本)
        if !hasImage && !hasFile {
            if let str = item.string(forType: .string) {
                let trimmed = str.trimmingCharacters(in: .whitespacesAndNewlines)
                if trimmed.isEmpty && item.data(forType: .rtf) == nil && item.data(forType: .html) == nil {
                    return true
                }
            }
        }

        return false
    }
}
